export const hongminDb = [
	{
		"date_at" : "2022-02-02",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-24",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-24",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-23",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-23",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-23",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-23",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-23",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-23",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	}
];

export const sabuDb = [
	{
		"date_at" : "2022-02-08",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 28,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 60,
		"sold_cnt" : 16,
		"use_cnt" : 4,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-02-06",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 28,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 60,
		"sold_cnt" : 16,
		"use_cnt" : 4,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-02-04",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 28,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 60,
		"sold_cnt" : 16,
		"use_cnt" : 4,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-02-04",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 28,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 60,
		"sold_cnt" : 16,
		"use_cnt" : 4,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-02-04",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 28,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 60,
		"sold_cnt" : 16,
		"use_cnt" : 4,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-02-04",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 28,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 60,
		"sold_cnt" : 16,
		"use_cnt" : 4,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-01-31",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 28,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 60,
		"sold_cnt" : 16,
		"use_cnt" : 4,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-01-24",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 27,
		"name" : "คูปองเงินสด 1000 บาท",
		"total_cnt" : 10,
		"sold_cnt" : 10,
		"use_cnt" : 0,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-01-23",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 27,
		"name" : "คูปองเงินสด 1000 บาท",
		"total_cnt" : 10,
		"sold_cnt" : 10,
		"use_cnt" : 0,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-01-17",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 27,
		"name" : "คูปองเงินสด 1000 บาท",
		"total_cnt" : 10,
		"sold_cnt" : 10,
		"use_cnt" : 0,
		"rest_brand_code" : "SYK"
	}
]
;

export const gingunjangDb = [
	{
		"date_at" : "2022-02-03",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-03",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-03",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-03",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-03",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-03",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-03",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-31",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-31",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-28",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-28",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-28",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-28",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-28",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-28",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-26",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-26",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-13",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	}
];