export const hongminDb = [
	{
		"date_at" : "2022-02-02",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-24",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-24",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-23",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-23",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-23",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-23",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-23",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-23",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-22",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	},
	{
		"date_at" : "2022-01-21",
		"brand_id" : 14,
		"brand_name" : "Hongmin",
		"master_coupon_id" : 19,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 120,
		"sold_cnt" : 120,
		"use_cnt" : 12,
		"rest_brand_code" : "HMN"
	}
];

export const sabuDb = [
	{
		"date_at" : "2022-02-08",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 28,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 60,
		"sold_cnt" : 16,
		"use_cnt" : 4,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-02-06",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 28,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 60,
		"sold_cnt" : 16,
		"use_cnt" : 4,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-02-04",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 28,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 60,
		"sold_cnt" : 16,
		"use_cnt" : 4,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-02-04",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 28,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 60,
		"sold_cnt" : 16,
		"use_cnt" : 4,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-02-04",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 28,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 60,
		"sold_cnt" : 16,
		"use_cnt" : 4,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-02-04",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 28,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 60,
		"sold_cnt" : 16,
		"use_cnt" : 4,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-01-31",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 28,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 60,
		"sold_cnt" : 16,
		"use_cnt" : 4,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-01-24",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 27,
		"name" : "คูปองเงินสด 1000 บาท",
		"total_cnt" : 10,
		"sold_cnt" : 10,
		"use_cnt" : 0,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-01-23",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 27,
		"name" : "คูปองเงินสด 1000 บาท",
		"total_cnt" : 10,
		"sold_cnt" : 10,
		"use_cnt" : 0,
		"rest_brand_code" : "SYK"
	},
	{
		"date_at" : "2022-01-17",
		"brand_id" : 20,
		"brand_name" : "Sabu Yakiniku",
		"master_coupon_id" : 27,
		"name" : "คูปองเงินสด 1000 บาท",
		"total_cnt" : 10,
		"sold_cnt" : 10,
		"use_cnt" : 0,
		"rest_brand_code" : "SYK"
	}
]
;

export const gingunjangDb = [
	{
		"date_at" : "2022-02-03",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-03",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-03",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-03",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-03",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-03",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-03",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-02-01",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-31",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-31",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-29",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-28",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-28",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-28",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-28",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-28",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-28",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-27",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-26",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-26",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	},
	{
		"date_at" : "2022-01-13",
		"brand_id" : 16,
		"brand_name" : "กินกันจัง Shabu Cheese",
		"master_coupon_id" : 22,
		"name" : "คูปองเงินสด 500 บาท",
		"total_cnt" : 60,
		"sold_cnt" : 60,
		"use_cnt" : 16,
		"rest_brand_code" : "GSH"
	}
];

export const saoLaoDb = [

];

export const moomuekkungDb = [
	{
		"date_at" : "2022-02-17",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1341,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-17",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1342,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-17",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1343,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-13",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1335,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-13",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1336,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-13",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : "2022-02-13 11:36:43",
		"rest_id" : 11709,
		"coupon_id" : 1331,
		"coupon_id" : 1331
	},
	{
		"date_at" : "2022-02-13",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1337,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-13",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1332,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-13",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1338,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-13",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1333,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-13",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1339,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-13",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1334,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-13",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1340,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-12",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1327,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-12",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1326,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1316,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : "2022-02-13 11:32:54",
		"rest_id" : 11709,
		"coupon_id" : 1311,
		"coupon_id" : 1311
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1322,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1317,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1312,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1323,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1318,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1313,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1324,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1319,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1314,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1309,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1325,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1320,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1315,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1310,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-02-11",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : "2022-02-15 11:11:07",
		"rest_id" : 11709,
		"coupon_id" : 1321,
		"coupon_id" : 1321
	},
	{
		"date_at" : "2022-01-31",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1308,
		"coupon_id" : null
	},
	{
		"date_at" : "2022-01-08",
		"brand_id" : 22,
		"brand_name" : "หมูหมึกกุ้งหมูกระทะ",
		"master_coupon_id" : 30,
		"name" : "คูปองเงินสด 500บาท",
		"total_cnt" : 120,
		"sold_cnt" : 33,
		"use_cnt" : 3,
		"rest_brand_code" : "MOK",
		"use_date" : null,
		"rest_id" : null,
		"coupon_id" : 1307,
		"coupon_id" : null
	}
]
;