import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

 function Home(props) {
  console.log(props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Ryoii Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
            Hello
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  // const data ={
  //   host: process.env.DB_HOST,
  //   username: process.env.DB_USER,
  //   password: process.env.DB_PASS,
  //   nextauth_url: process.env.NEXTAUTH_URL,
  // }
  const { NEXTAUTH_URL } = process.env;
  const res = await fetch(NEXTAUTH_URL+'/api/hello')
  const data = await res.json()
  return { props:  data  }
}

export default Home